# Generated by Django 3.0.7 on 2020-06-19 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='manger',
            new_name='manager',
        ),
    ]
