# Generated by Django 3.0.7 on 2020-06-25 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productbatch',
            old_name='Paid_for',
            new_name='paid_for',
        ),
    ]
