# Generated by Django 3.0.7 on 2020-06-17 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200617_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_bunch',
            name='date_purchased',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_bunch',
            name='quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product_bunch',
            name='shop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.Shop'),
        ),
    ]
