# Generated by Django 3.0.7 on 2020-06-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200625_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsales',
            name='item',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
