# Generated by Django 3.0.7 on 2020-06-17 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200617_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buying_price', models.IntegerField(null=True)),
                ('date_received', models.DateField(auto_now_add=True)),
                ('damaged_items', models.IntegerField(null=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('clerk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.Clerk')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.Item')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('selling_price', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.Item')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Shop')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=20, null=True)),
                ('supplier_contant', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Product_Bunch',
        ),
        migrations.AddField(
            model_name='productbatch',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Supplier'),
        ),
    ]
